tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
]

tasks/models.py
from django.db import models
from django.utils import timezone

class Tasks(models.Model):
    task = models.CharField(max_length=100)
    posted_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.task

tasks/views.py
from django.shortcuts import render, redirect
from .models import Tasks
from datetime import date
from django import forms
from django.views.decorators.http import require_POST

today = date.today()

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

context = {'tasks':Tasks.objects.all(),'date':today.strftime("%B %d, %Y")}

def home(request):
    return render(request, 'tasks/home.html', context)

@require_POST
def add(request):
    if request.method == 'POST':
        data = request.POST['newItem']
        task = Tasks(task = data)
        task.save()
    return redirect('tasks:home')

@require_POST
def delete(request):
    if request.method == 'POST':
        data = request.POST['checkbox']
        Tasks.objects.filter(id=data).delete()
    return redirect('tasks:home')

tasks/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static '/tasks/styles.css' %}">
    <title>TodoList</title>
</head>
<body>
    {% block content %}{% endblock %}
    <footer>
        Copyright 2021 Burak Ilhan
    </footer>
</body>
</html>

tasks/templates/tasks/home.html
{% extends 'tasks/base.html' %}
{% block content %}
<div class="box" id="heading">
    <h1>{{date}}</h1>
</div>
<div class="box">
    {% for task in tasks %}
    <form action="{% url 'tasks:delete' %}" method="post">
        {% csrf_token %}
    <div class="item">
        <input type="checkbox" name="checkbox" value="{{task.id}}" onChange="this.form.submit()">
        <p>{{task.task}}</p>
    </div>
    <input type="hidden" name="listName" value=""></input>
    </form>
    {% endfor %}
    <form class="item" action="{% url 'tasks:add' %}" , method="post">
        {% csrf_token %}
        <input type="text" name="newItem" placeholder="New Item" autocomplete="off">
        <button type="submit" name="list">+</button>
    </form>
</div>
{% endblock %}